-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 16:42:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library-century
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library-century
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library-century` DEFAULT CHARACTER SET utf8 ;
USE `library-century` ;

-- -----------------------------------------------------
-- Table `library-century`.`editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`editors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`books` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `publishing_date` DATE NOT NULL,
  `summary` TEXT NOT NULL,
  `picture` VARCHAR(255) NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `editor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `editor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`authors` (
  `id` INT(11) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL DEFAULT '250',
  `firstname` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `biography` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`book_authors` (
  `id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  `author_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `book_id`, `author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`styles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`book_styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`book_styles` (
  `id` INT(11) NOT NULL,
  `style_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `style_id`, `book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`formats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`formats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`book_formats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`book_formats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `format_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `format_id`, `book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library-century`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library-century`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
